title: 420360 Blog
description: A Simple Blog for 420360
author: Stephanus
email: woodmurderedhat@gmail.com

# GitHub Pages settings
github: [metadata]
url: https://woodmurderedhat.github.io
baseurl: /blog420

# Jekyll settings
markdown: kramdown
permalink: /:year/:month/:day/:title/
excerpt_separator: "<!--more-->"

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-feed

# Collections
collections:
  - drafts

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Your Name"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - .gitignore
  - node_modules
